name: _Reusable Android Build

on:
  workflow_call:
    inputs:
      gradle-args:
        description: 実行する Gradle タスクのリスト（スペース区切り）
        required: true
        type: string
      working-directory:
        description: Gradle 実行ディレクトリ
        required: false
        default: .
        type: string
      upload-artifact:
        description: 成果物をアップロードするかどうか
        required: false
        default: false
        type: boolean
      artifact-name:
        description: アーティファクト名（upload-artifact=true の場合）
        required: false
        default: build-artifacts
        type: string
      artifact-path:
        description: アーティファクトとして保存するパス
        required: false
        default: "app/build/outputs"
        type: string
      ci-version-minor:
        description: CI で上書きするマイナーバージョン
        required: false
        default: ""
        type: string
      ci-version-patch:
        description: CI で上書きするパッチバージョン
        required: false
        default: ""
        type: string
    secrets:
      MAPS_API_KEY:
        required: false
      PLAY_SERVICE_ACCOUNT_JSON:
        required: false
      ANDROID_KEYSTORE_BASE64:
        required: false
      ANDROID_KEYSTORE_PASSWORD:
        required: false
      ANDROID_KEY_ALIAS:
        required: false
      ANDROID_KEY_ALIAS_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_VERSION_MINOR: ${{ inputs.ci-version-minor }}
      CI_VERSION_PATCH: ${{ inputs.ci-version-patch }}
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: JDK をセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Gradle キャッシュを構成
        uses: gradle/actions/setup-gradle@v4

      - name: Android SDK をセットアップ
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          components: |
            platforms;android-36
            build-tools;36.0.0

      - name: Gradle ラッパーに実行権限を付与
        run: chmod +x ./gradlew
        working-directory: ${{ inputs.working-directory }}

      - name: Secrets をファイルへ書き出し
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          set -euo pipefail
          if [[ -n "${{ secrets.MAPS_API_KEY }}" ]]; then
            printf 'MAPS_API_KEY=%s\n' "${{ secrets.MAPS_API_KEY }}" > local.properties
          fi
          mkdir -p gradle
          if [[ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]]; then
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > gradle/keystore.jks
          fi
          if [[ -n "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" ]]; then
            printf '%s' "${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}" > gradle/play-service-account.json
          fi

      - name: Gradle タスクを実行
        working-directory: ${{ inputs.working-directory }}
        run: ./gradlew ${{ inputs.gradle-args }} --stacktrace --no-daemon

      - name: 成果物をアップロード
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          if-no-files-found: warn

      - name: Secrets ファイルを削除
        if: always()
        shell: bash
        working-directory: ${{ inputs.working-directory }}
        run: |
          rm -f local.properties
          rm -f gradle/keystore.jks
          rm -f gradle/play-service-account.json
