name: Android CI

on:
  push:
    branches-ignore:
      - main
      - release

jobs:
  build:
    uses: ./.github/workflows/_reusable-android-build.yml
    with:
      gradle-args: "test assembleDebug"
      upload-artifact: true
      artifact-name: debug-build
      artifact-path: |
        app/build/outputs/apk/debug
        app/build/reports/tests
    secrets:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
