name: Android Promote

on:
  push:
    branches:
      - release

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: 内部テストを製品版に昇格
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: promoteReleaseArtifact --from-track internal --promote-track production --release-status completed
          maps-api-key: ${{ secrets.MAPS_API_KEY }}
          play-service-account-json: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          android-key-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          android-key-alias-password: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
