name: Android CI

on:
  push:
    branches-ignore:
      - main
      - release

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Unitテスト・デバッグビルド
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: testDebugUnitTest assembleDebug
          maps-api-key: ${{ secrets.MAPS_API_KEY }}

      - name: テストレポートをアップロード
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Unit Test Report
          path: app/build/test-results/**/TEST-*.xml
          reporter: java-junit
          fail-on-error: false
          list-suites: failed
          list-tests: failed
          use-actions-summary: true

  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Lint 実行
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: lintDebug
          maps-api-key: ${{ secrets.MAPS_API_KEY }}

      - name: Lint レポートを保存
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            app/build/reports/lint-results-debug.html
            app/build/reports/lint-results-debug.xml
          if-no-files-found: warn
          retention-days: 1
