name: Android CI

on:
  push:
    branches-ignore:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Unitテスト
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: test
          maps-api-key: ${{ secrets.MAPS_API_KEY }}

      - name: デバッグ成果物をアップロード
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-build
          path: |
            app/build/reports/tests
          if-no-files-found: warn
