name: Android Promote

on:
  push:
    branches:
      - release

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Android SDK キャッシュを復元
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk/build-tools
            /usr/local/lib/android/sdk/platforms
            /usr/local/lib/android/sdk/platform-tools
            ~/.android
          key: android-sdk-${{ runner.os }}-${{ hashFiles('gradle/libs.versions.toml') }}

      - name: チェックアウト
        uses: actions/checkout@v4

      - name: 内部テストを製品版に昇格
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: promoteReleaseArtifact --from-track internal --promote-track production --release-status completed
          maps-api-key: ${{ secrets.MAPS_API_KEY }}
          play-service-account-json: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          android-keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          android-keystore-password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          android-key-alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          android-key-alias-password: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
          required-build-tools: 36.0.0
          required-platforms: android-36
          ensure-android-components: 'true'
