name: Android CI

on:
  push:
    branches-ignore:
      - main
      - release

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Unitテスト・カバレッジレポート生成
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: testDebugUnitTest jacocoTestReport
          maps-api-key: ${{ secrets.MAPS_API_KEY }}

      - name: Jacoco レポートを保存
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport
          if-no-files-found: warn
          retention-days: 1

  lint:
    name: Android Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: Lint 実行
        uses: ./.github/actions/android-gradle
        with:
          gradle-args: lintDebug
          maps-api-key: ${{ secrets.MAPS_API_KEY }}

      - name: Lint レポートを保存
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: |
            app/build/reports/lint-results-debug.html
            app/build/reports/lint-results-debug.xml
          if-no-files-found: warn
          retention-days: 1
