name: Android Release PR

on:
  pull_request:
    branches:
      - release

jobs:
  unit:
    name: ユニットテスト
    uses: ./.github/workflows/_reusable-android-build.yml
    with:
      gradle-args: "test"
      ci-version-minor: ${{ github.event.pull_request.number }}
      ci-version-patch: ${{ github.run_number }}
    secrets:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

  connected:
    name: 計装テスト
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 35]
    env:
      CI_VERSION_MINOR: ${{ github.event.pull_request.number }}
      CI_VERSION_PATCH: ${{ github.run_number }}
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: JDK をセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle キャッシュを構成
        uses: gradle/actions/setup-gradle@v4

      - name: Secrets をファイルへ書き出し
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ secrets.MAPS_API_KEY }}" ]]; then
            cat <<'PROP' > local.properties
MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
PROP
          fi

          mkdir -p gradle
          if [[ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]]; then
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > gradle/keystore.jks
          fi

      - name: 計装テストを実行
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          script: ./gradlew connectedDebugAndroidTest --stacktrace --no-daemon

      - name: テストレポートをアップロード
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: androidTest-${{ matrix.api-level }}
          path: app/build/reports/androidTests
          if-no-files-found: warn

      - name: Secrets ファイルを削除
        if: always()
        run: |
          rm -f local.properties
          rm -f gradle/keystore.jks

  firebase-test:
    name: Firebase Test Lab
    needs: unit
    if: ${{ secrets.FIREBASE_TEST_LAB_SA_JSON != '' }}
    runs-on: ubuntu-latest
    env:
      CI_VERSION_MINOR: ${{ github.event.pull_request.number }}
      CI_VERSION_PATCH: ${{ github.run_number }}
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4

      - name: JDK をセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle キャッシュを構成
        uses: gradle/actions/setup-gradle@v4

      - name: Firebase 用のバンドルを作成
        run: ./gradlew bundleRelease --stacktrace --no-daemon

      - name: Firebase Test Lab へ送信
        uses: wzieba/firebase-test-lab@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_TEST_LAB_SA_JSON }}
          gcloud_command: test android run --type instrumentation --app app/build/outputs/bundle/release/app-release.aab

  publish:
    name: 内部テストへアップロード
    needs: [unit, connected]
    uses: ./.github/workflows/_reusable-android-build.yml
    with:
      gradle-args: "bundleRelease publishReleaseBundle"
      upload-artifact: true
      artifact-name: release-build
      artifact-path: app/build/outputs/bundle/release
      ci-version-minor: ${{ github.event.pull_request.number }}
      ci-version-patch: ${{ github.run_number }}
    secrets:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}
